# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15lh6tfry93t4BeJ5Wccgx8vczOvLwqne
"""



"""Programa que suma 2 números"""

# Leer 2 números y mostrar la suma
n1 = int(input("Ingrese el primer número: "))
n2 = int(input("Ingrese el segundo número: "))
suma = n1 + n2
print ("La suma es: ", suma)

"""Condiciones dobles."""

edad = int (input ("Ingrese su edad: "))
if edad >=18:
  mje = "Es mayor de edad"

else:
  mje = "Es menor de edad"

print(mje)

"""Promedio y Evaluacion de Aprobacion"""

from posixpath import realpath
#Leer 3 numeros y mostrar el promedio
n1 = int(input("Ingrese la primera nota"))
n2 = int(input("Ingrese la segunda nota"))
n3 = int(input("Ingrese la tercera nota"))

#Operacion de hallar el promedio de las 3 notas
suma = n1 + n2 + n3
promedio  = suma /3

print ("El promedio de las notas es: ", promedio)

#Evaluacion si esta aprobado o desaprobado >=11

if promedio >=11:
  mje = "Aprobado"

else:
  mje = "Desaprobado"

print(mje)